"""Configuration used for artifacts/overfitting-run.txt."""

CORPUS_PATH = "data/raw/notes.txt"
AUGMENTED_CORPUS_PATH = "data/generated/augmented_notes.txt"
PARAPHRASE_PROGRESS_PATH = "data/generated/paraphrases.jsonl"
TOKENIZER_PATH = "tokenizer.json"
CHECKPOINT_PATH = "model.pt"

PARAPHRASE_MODEL = "gpt-5-mini"
PARAPHRASE_VARIANTS = 2
PARAPHRASE_CHUNK_CHARACTERS = 12_000
PARAPHRASE_MAX_OUTPUT_TOKENS = 6_000

END_OF_TEXT = 256
VOCAB_SIZE = 1024

CONTEXT_LENGTH = 256
EMBEDDING_SIZE = 384
NUMBER_OF_HEADS = 6
NUMBER_OF_BLOCKS = 6
FEED_FORWARD_MULTIPLIER = 4
DROPOUT = 0.0
WEIGHT_INIT_STD = 0.02

BATCH_SIZE = 16
TRAINING_STEPS = 2000
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 0.1
TRAINING_FRACTION = 0.9
EVALUATION_INTERVAL = 100
EVALUATION_BATCHES = 10
TRAINING_SAMPLE_TOKENS = 50
RANDOM_SEED = 42

DEFAULT_PROMPT = "i think"
TOKENS_TO_GENERATE = 200
TEMPERATURE = 0.8
