"""Configuration used for artifacts/regularized-run.txt."""

CORPUS_PATH = "data/raw/notes.txt"
AUGMENTED_CORPUS_PATH = "data/generated/augmented_notes.txt"
PARAPHRASE_PROGRESS_PATH = "data/generated/paraphrases.jsonl"
TOKENIZER_PATH = "tokenizer.json"
CHECKPOINT_PATH = "model.pt"

PARAPHRASE_MODEL = "gpt-5-mini"
PARAPHRASE_VARIANTS = 2
PARAPHRASE_CHUNK_CHARACTERS = 12_000
PARAPHRASE_MAX_OUTPUT_TOKENS = 6_000

END_OF_TEXT = 256
VOCAB_SIZE = 1024

CONTEXT_LENGTH = 256
EMBEDDING_SIZE = 256
NUMBER_OF_HEADS = 4
NUMBER_OF_BLOCKS = 4
FEED_FORWARD_MULTIPLIER = 4
DROPOUT = 0.1
WEIGHT_INIT_STD = 0.02

BATCH_SIZE = 32
TRAINING_STEPS = 3000
LEARNING_RATE = 3e-4
MINIMUM_LEARNING_RATE = 3e-5
WARMUP_STEPS = 100
LEARNING_RATE_DECAY_STEPS = 3000
WEIGHT_DECAY = 0.1
TRAINING_FRACTION = 0.9
EVALUATION_INTERVAL = 100
EVALUATION_BATCHES = 20
TRAINING_SAMPLE_TOKENS = 50
RANDOM_SEED = 42

DEFAULT_PROMPT = "- i think"
TOKENS_TO_GENERATE = 200
TEMPERATURE = 0.7
